steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://tmp_tillman/models/*', './models']

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us.gcr.io/sentryio/seer:$COMMIT_SHA', '.' ]

# This is needed for Freight to find matching builds
images: ['us.gcr.io/sentryio/seer:$COMMIT_SHA']
