services:
    app:
        image: us-west1-docker.pkg.dev/${SBX_PROJECT}/staging/seer
        volumes: !reset []
        command:
            - bash
            - -c
            - |
              flask db upgrade
              exec /usr/bin/supervisord -c /etc/supervisord.conf
