services:
    build: null
    app:
        image: us-west1-docker.pkg.dev/${SBX_PROJECT}/staging/seer
        command: bash -c "
            flask db upgrade
            exec /usr/bin/supervisord -c /etc/supervisord.conf
            "
