"""Migration

Revision ID: 0226c3793a61
Revises:
Create Date: 2024-02-09 14:01:48.518223

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0226c3793a61"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "process_request",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(), nullable=False),
        sa.Column("scheduled_from", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("process_request", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_process_request_name"), ["name"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_process_request_scheduled_for"), ["scheduled_for"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("process_request", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_process_request_scheduled_for"))
        batch_op.drop_index(batch_op.f("ix_process_request_name"))

    op.drop_table("process_request")
    # ### end Alembic commands ###
