"""UploadLocking

Revision ID: 02ebff8795d3
Revises: 02827f37e51d
Create Date: 2025-05-12 15:48:56.133303

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "02ebff8795d3"
down_revision = "02827f37e51d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("seer_repo_archive", schema=None) as batch_op:
        batch_op.add_column(sa.Column("upload_locked_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("seer_repo_archive", schema=None) as batch_op:
        batch_op.drop_column("upload_locked_at")

    # ### end Alembic commands ###
