"""Migration

Revision ID: 09b3ef05f1fe
Revises: da0a9c9f1bb4
Create Date: 2024-09-17 17:13:49.660584

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "09b3ef05f1fe"
down_revision = "da0a9c9f1bb4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.alter_column("message", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.alter_column("message", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###
