"""SeerPreferences

Revision ID: 14b69932f015
Revises: f1970ed945bd
Create Date: 2025-03-21 17:40:45.683977

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "14b69932f015"
down_revision = "f1970ed945bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "seer_project_preferences",
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("repositories", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("project_id"),
        sa.UniqueConstraint("organization_id", "project_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("seer_project_preferences")
    # ### end Alembic commands ###
