"""chore(anomaly_detection): add support for source based alert ids

Revision ID: 21051ea8b612
Revises: b27f28d90e1a
Create Date: 2025-06-01 02:13:21.789710

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "21051ea8b612"
down_revision = "b27f28d90e1a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dynamic_alert_time_series_history", schema=None) as batch_op:
        batch_op.drop_constraint("dynamic_alert_time_series_history_pkey", type_="primary")
        batch_op.add_column(sa.Column("external_alert_source_id", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("external_alert_source_type", sa.BigInteger(), nullable=True))
        batch_op.alter_column("alert_id", existing_type=sa.BIGINT(), nullable=True)
        batch_op.create_primary_key(
            "dynamic_alert_time_series_history_pkey",
            ["id"],
        )

    with op.batch_alter_table("dynamic_alerts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("external_alert_source_id", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("external_alert_source_type", sa.BigInteger(), nullable=True))
        batch_op.alter_column("external_alert_id", existing_type=sa.BIGINT(), nullable=True)
        batch_op.drop_constraint("dynamic_alerts_external_alert_id_key", type_="unique")
        batch_op.drop_index("ix_dynamic_alert_external_alert_id")
        batch_op.create_index(
            "ix_dynamic_alert_external_alert_id_source_id_source_type",
            ["external_alert_id", "external_alert_source_id", "external_alert_source_type"],
            unique=True,
        )

    with op.batch_alter_table("prophet_alert_time_series_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("external_alert_source_id", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("external_alert_source_type", sa.BigInteger(), nullable=True))
        batch_op.alter_column("alert_id", existing_type=sa.BIGINT(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prophet_alert_time_series_history", schema=None) as batch_op:
        batch_op.alter_column("alert_id", existing_type=sa.BIGINT(), nullable=False)
        batch_op.drop_column("external_alert_source_type")
        batch_op.drop_column("external_alert_source_id")

    with op.batch_alter_table("dynamic_alerts", schema=None) as batch_op:
        batch_op.drop_index("ix_dynamic_alert_external_alert_id_source_id_source_type")
        batch_op.create_index(
            "ix_dynamic_alert_external_alert_id", ["external_alert_id"], unique=False
        )
        batch_op.create_unique_constraint(
            "dynamic_alerts_external_alert_id_key", ["external_alert_id"]
        )
        batch_op.alter_column("external_alert_id", existing_type=sa.BIGINT(), nullable=False)
        batch_op.drop_column("external_alert_source_type")
        batch_op.drop_column("external_alert_source_id")

    with op.batch_alter_table("dynamic_alert_time_series_history", schema=None) as batch_op:
        # There is no going back to old primary key as alert_id is now nullable.
        # Also we do not need alert id as primary key anyways.
        batch_op.alter_column("alert_id", existing_type=sa.BIGINT(), nullable=False)
        batch_op.drop_column("external_alert_source_type")
        batch_op.drop_column("external_alert_source_id")

    # ### end Alembic commands ###
