"""repo_archive_updated_at

Revision ID: 2a18f50acae3
Revises: 6d2311bec270
Create Date: 2025-05-27 19:53:22.278337

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import func

# revision identifiers, used by Alembic.
revision = "2a18f50acae3"
down_revision = "6d2311bec270"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("seer_repo_archive", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=func.now())
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("seer_repo_archive", schema=None) as batch_op:
        batch_op.drop_column("updated_at")

    # ### end Alembic commands ###
