"""Migration

Revision ID: 2df77dc3a696
Revises: 6caab02760db
Create Date: 2024-08-20 17:18:33.399435

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2df77dc3a696"
down_revision = "6caab02760db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run_state", schema=None) as batch_op:
        batch_op.add_column(sa.Column("type", sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run_state", schema=None) as batch_op:
        batch_op.drop_column("type")

    # ### end Alembic commands ###
