"""Migration

Revision ID: 2e22d272d3b8
Revises: 96e56e375579
Create Date: 2024-09-02 23:08:36.978554

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2e22d272d3b8"
down_revision = "96e56e375579"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issue_summary",
        sa.Column("group_id", sa.BigInteger(), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("group_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("issue_summary")
    # ### end Alembic commands ###
