"""Migration

Revision ID: 34e1f6a6297a
Revises: 1eadd11b67ed
Create Date: 2024-02-26 22:03:21.527166

"""

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector  # type: ignore

# revision identifiers, used by Alembic.
revision = "34e1f6a6297a"
down_revision = "1eadd11b67ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grouping_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.BigInteger(), nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("stacktrace_embedding", Vector(dim=768), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.create_index("ix_grouping_records_project_id", ["project_id"], unique=False)
        batch_op.create_index(
            "ix_grouping_records_stacktrace_embedding_hnsw",
            ["stacktrace_embedding"],
            unique=False,
            postgresql_using="hnsw",
            postgresql_with={"m": 16, "ef_construction": 64},
            postgresql_ops={"stacktrace_embedding": "vector_cosine_ops"},
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.drop_index(
            "ix_grouping_records_stacktrace_embedding_hnsw",
            postgresql_using="hnsw",
            postgresql_with={"m": 16, "ef_construction": 64},
            postgresql_ops={"stacktrace_embedding": "vector_cosine_ops"},
        )
        batch_op.drop_index("ix_grouping_records_project_id")

    op.drop_table("grouping_records")
    # ### end Alembic commands ###
