"""Migration

Revision ID: 3914e6cdb818
Revises: 62facff812cc
Create Date: 2024-10-28 16:34:04.779389

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3914e6cdb818"
down_revision = "62facff812cc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.drop_column("message")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.add_column(sa.Column("message", sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
