"""Migration

Revision ID: 49e9388dfd85
Revises: 1eadd11b67ed
Create Date: 2024-02-26 05:36:24.659279

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "49e9388dfd85"
down_revision = "1eadd11b67ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grouping_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("stacktrace_embedding", pgvector.sqlalchemy.Vector(dim=768), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.create_index("ix_grouping_records_project_id", ["project_id"], unique=False)
        batch_op.create_index(
            "ix_grouping_records_stacktrace_embedding_hnsw",
            ["stacktrace_embedding"],
            unique=False,
            postgresql_using="hnsw",
            postgresql_with={"m": 16, "ef_construction": 64},
            postgresql_ops={"stacktrace_embedding": "vector_cosine_ops"},
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.drop_index(
            "ix_grouping_records_stacktrace_embedding_hnsw",
            postgresql_using="hnsw",
            postgresql_with={"m": 16, "ef_construction": 64},
            postgresql_ops={"stacktrace_embedding": "vector_cosine_ops"},
        )
        batch_op.drop_index("ix_grouping_records_project_id")

    op.drop_table("grouping_records")
    # ### end Alembic commands ###
