"""Migration

Revision ID: 49f6aa3ad4e3
Revises: f77d67f765e5
Create Date: 2024-06-11 21:28:07.825544

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "49f6aa3ad4e3"
down_revision = "f77d67f765e5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.add_column(sa.Column("error_type", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.drop_column("error_type")

    # ### end Alembic commands ###
