"""Migration

Revision ID: 4a87188db505
Revises: 9ac60c7534ce
Create Date: 2025-05-22 22:45:51.495835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a87188db505'
down_revision = '9ac60c7534ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_state', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
