"""Migration

Revision ID: 5132375cef7e
Revises: 5bc8ec908849
Create Date: 2024-02-29 21:30:28.646335

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5132375cef7e"
down_revision = "5bc8ec908849"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_tombstones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repo_id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("namespace", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["repo_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table("document_chunk_tombstones", schema=None) as batch_op:
        batch_op.drop_index("idx_repo_namespace_path")

    with op.batch_alter_table("document_tombstones", schema=None) as batch_op:
        batch_op.create_index(
            "idx_repo_namespace_path", ["repo_id", "namespace", "path"], unique=True
        )

    op.drop_table("document_chunk_tombstones")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_chunk_tombstones",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("repo_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("path", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("namespace", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"], ["repositories.id"], name="document_chunk_tombstones_repo_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="document_chunk_tombstones_pkey"),
    )
    with op.batch_alter_table("document_chunk_tombstones", schema=None) as batch_op:
        batch_op.create_index(
            "idx_repo_namespace_path", ["repo_id", "namespace", "path"], unique=True
        )

    with op.batch_alter_table("document_tombstones", schema=None) as batch_op:
        batch_op.drop_index("idx_repo_namespace_path")

    op.drop_table("document_tombstones")
    # ### end Alembic commands ###
