"""Migration

Revision ID: 52d271c30ee5
Revises: e0fcdc14251c
Create Date: 2025-02-28 23:53:40.954667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d271c30ee5'
down_revision = 'e0fcdc14251c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codegen_unit_test_generation_pr_context_to_run_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('pr_id', sa.BigInteger(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run_state.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'pr_id', 'repo', 'owner')
    )
    with op.batch_alter_table('codegen_unit_test_generation_pr_context_to_run_id', schema=None) as batch_op:
        batch_op.create_index('ix_autofix_repo_owner_pr_id', ['owner', 'repo', 'pr_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codegen_unit_test_generation_pr_context_to_run_id', schema=None) as batch_op:
        batch_op.drop_index('ix_autofix_repo_owner_pr_id')

    op.drop_table('codegen_unit_test_generation_pr_context_to_run_id')
    # ### end Alembic commands ###
