"""Migration

Revision ID: 52d3b519f90c
Revises: 1eadd11b67ed
Create Date: 2024-02-28 20:51:40.570163

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "52d3b519f90c"
down_revision = "1eadd11b67ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("namespace", sa.String(length=36), nullable=True))
        batch_op.drop_column("for_run_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("for_run_id", sa.VARCHAR(length=36), autoincrement=False, nullable=True)
        )
        batch_op.drop_column("namespace")

    # ### end Alembic commands ###
