"""DbSeerRepoArchive

Revision ID: 52f49ca9d363
Revises: 17f604dbf6c5
Create Date: 2025-05-13 08:18:26.079744

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "52f49ca9d363"
down_revision = "17f604dbf6c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "seer_repo_archive",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("bucket_name", sa.String(), nullable=False),
        sa.Column("blob_path", sa.String(), nullable=False),
        sa.Column("commit_sha", sa.String(), nullable=False),
        sa.Column("upload_locked_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "bucket_name", "blob_path"),
    )
    with op.batch_alter_table("seer_repo_archive", schema=None) as batch_op:
        batch_op.create_index(
            "ix_seer_repo_archive_org_id_bucket_name_blob_path",
            ["organization_id", "bucket_name", "blob_path"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("seer_repo_archive", schema=None) as batch_op:
        batch_op.drop_index("ix_seer_repo_archive_org_id_bucket_name_blob_path")

    op.drop_table("seer_repo_archive")
    # ### end Alembic commands ###
