"""Migration

Revision ID: 5bc8ec908849
Revises: dc4a781d8e04
Create Date: 2024-02-29 20:52:40.535098

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5bc8ec908849"
down_revision = "dc4a781d8e04"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.drop_index(
            "idx_repo_id_namespace_path", postgresql_where="(namespace IS NOT NULL)"
        )
        batch_op.create_index(
            "idx_repo_id_namespace_path",
            ["repo_id", "namespace", "path"],
            unique=False,
            postgresql_where=sa.text("namespace IS NOT NULL"),
        )
        batch_op.drop_index("idx_repo_path", postgresql_where="(namespace IS NULL)")
        batch_op.create_index(
            "idx_repo_path",
            ["repo_id", "path"],
            unique=False,
            postgresql_where=sa.text("namespace IS NULL"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.drop_index("idx_repo_path", postgresql_where=sa.text("namespace IS NULL"))
        batch_op.create_index(
            "idx_repo_path",
            ["repo_id", "path"],
            unique=True,
            postgresql_where="(namespace IS NULL)",
        )
        batch_op.drop_index(
            "idx_repo_id_namespace_path", postgresql_where=sa.text("namespace IS NOT NULL")
        )
        batch_op.create_index(
            "idx_repo_id_namespace_path",
            ["repo_id", "namespace", "path"],
            unique=True,
            postgresql_where="(namespace IS NOT NULL)",
        )

    # ### end Alembic commands ###
