"""Migration

Revision ID: 62facff812cc
Revises: 88ba967e2102
Create Date: 2024-09-26 04:44:25.614375

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "62facff812cc"
down_revision = "88ba967e2102"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dynamic_alerts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "data_purge_flag",
                sa.Enum("NOT_QUEUED", "PROCESSING", "QUEUED", name="taskstatus", native_enum=False),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("last_queued_at", sa.DateTime(), nullable=True))
    op.execute("UPDATE dynamic_alerts SET data_purge_flag = 'NOT_QUEUED'")
    op.alter_column("dynamic_alerts", "data_purge_flag", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dynamic_alerts", schema=None) as batch_op:
        batch_op.drop_column("last_queued_at")
        batch_op.drop_column("data_purge_flag")

    # ### end Alembic commands ###
