"""repo_sync_cursor

Revision ID: 6d2311bec270
Revises: 9ac60c7534ce
Create Date: 2025-05-27 19:03:14.410406

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6d2311bec270"
down_revision = "9ac60c7534ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("seer_backfill_state", schema=None) as batch_op:
        # First add the column as nullable with default
        batch_op.add_column(
            sa.Column("repo_sync_cursor", sa.BigInteger(), nullable=True, default=0)
        )

    # Update existing rows to have the default value
    op.execute("UPDATE seer_backfill_state SET repo_sync_cursor = 0 WHERE repo_sync_cursor IS NULL")

    # Now make the column not null and apply other changes
    with op.batch_alter_table("seer_backfill_state", schema=None) as batch_op:
        batch_op.alter_column("repo_sync_cursor", existing_type=sa.BigInteger(), nullable=False)
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            type_=sa.BigInteger(),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "backfill_cursor",
            existing_type=sa.INTEGER(),
            type_=sa.BigInteger(),
            existing_nullable=False,
            server_default="0",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("seer_backfill_state", schema=None) as batch_op:
        batch_op.alter_column(
            "backfill_cursor",
            existing_type=sa.BigInteger(),
            type_=sa.INTEGER(),
            existing_nullable=False,
            server_default=None,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger(),
            type_=sa.INTEGER(),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.drop_column("repo_sync_cursor")

    # ### end Alembic commands ###
