"""Migration

Revision ID: 7278a2303b10
Revises: 34eef02b2555
Create Date: 2024-05-02 15:56:39.243317

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7278a2303b10"
down_revision = "34eef02b2555"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "hash",
                sa.String(length=32),
                server_default="00000000000000000000000000000000",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.drop_column("hash")

    # ### end Alembic commands ###
