"""Migration

Revision ID: 79bc3049dbe5
Revises: 913d11ce1bea
Create Date: 2024-04-18 17:17:30.802314

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "79bc3049dbe5"
down_revision = "913d11ce1bea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "group_hash",
                sa.String(length=32),
                server_default="00000000000000000000000000000000",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.drop_column("group_hash")

    # ### end Alembic commands ###
