"""Migration

Revision ID: 853bee2403b5
Revises: aeeaf482e659
Create Date: 2024-09-04 18:32:45.751736

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "853bee2403b5"
down_revision = "aeeaf482e659"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("autofix_pr_id_to_run_id", schema=None) as batch_op:
        batch_op.drop_constraint("autofix_pr_id_to_run_id_run_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key(None, "run_state", ["run_id"], ["id"], ondelete="CASCADE")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("autofix_pr_id_to_run_id", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "autofix_pr_id_to_run_id_run_id_fkey", "run_state", ["run_id"], ["id"]
        )

    # ### end Alembic commands ###
