"""Seer event logging

Revision ID: 8548b504edfe
Revises: 86ba1a6c0cc3
Create Date: 2025-02-19 23:46:26.738816

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8548b504edfe"
down_revision = "86ba1a6c0cc3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "seer_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("event_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("seer_events")
    # ### end Alembic commands ###
