"""Migration

Revision ID: 88ba967e2102
Revises: 09b3ef05f1fe
Create Date: 2024-09-23 18:25:21.391260

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "88ba967e2102"
down_revision = "09b3ef05f1fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "run_memory",
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["run_state.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id"),
    )
    with op.batch_alter_table("run_memory", schema=None) as batch_op:
        batch_op.create_index("ix_run_memory_run_id", ["run_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run_memory", schema=None) as batch_op:
        batch_op.drop_index("ix_run_memory_run_id")

    op.drop_table("run_memory")
    # ### end Alembic commands ###
