"""Migration

Revision ID: 8b220c343d13
Revises: 0a992db1f362
Create Date: 2024-06-05 23:33:29.779267

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8b220c343d13"
down_revision = "0a992db1f362"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.create_index(
            "ix_grouping_records_project_id_hash", ["project_id", "hash"], unique=True
        )
        batch_op.create_unique_constraint(None, ["project_id", "hash"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_index("ix_grouping_records_project_id_hash")

    # ### end Alembic commands ###
