"""Migration

Revision ID: 96e56e375579
Revises: 6caab02760db
Create Date: 2024-08-14 22:27:16.086269

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "96e56e375579"
down_revision = "6caab02760db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "smoke_tests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("smoke_tests", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_smoke_tests_request_id"), ["request_id"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("smoke_tests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_smoke_tests_request_id"))

    op.drop_table("smoke_tests")
    # ### end Alembic commands ###
