"""Create backfill job

Revision ID: 9ac60c7534ce
Revises: 52f49ca9d363
Create Date: 2025-05-16 11:19:19.729339

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9ac60c7534ce"
down_revision = "52f49ca9d363"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "seer_backfill_job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("repo_provider", sa.String(), nullable=False),
        sa.Column("repo_external_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.Column("failed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "repo_provider", "repo_external_id"),
    )
    op.create_table(
        "seer_backfill_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("backfill_cursor", sa.Integer(), nullable=False),
        sa.Column("task_taken_key", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("seer_backfill_state")
    op.drop_table("seer_backfill_job")
    # ### end Alembic commands ###
