"""Migration

Revision ID: a0d00121d118
Revises: d1214acbe7bc
Create Date: 2024-06-14 17:20:04.764888

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a0d00121d118"
down_revision = "d1214acbe7bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.add_column(sa.Column("error_type", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.drop_column("error_type")

    # ### end Alembic commands ###
