"""chore(anomaly_detection): add support for source based alert ids

Revision ID: aa83206907cc
Revises: b27f28d90e1a
Create Date: 2025-05-30 21:31:10.857583

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "aa83206907cc"
down_revision = "b27f28d90e1a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dynamic_alert_time_series_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("external_alert_source_id", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("external_alert_source_type", sa.BigInteger(), nullable=True))

    with op.batch_alter_table("dynamic_alerts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("external_alert_source_id", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("external_alert_source_type", sa.BigInteger(), nullable=True))
        batch_op.create_index(
            "ix_dynamic_alert_external_alert_source_id_source_type",
            ["external_alert_source_id", "external_alert_source_type"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dynamic_alerts", schema=None) as batch_op:
        batch_op.drop_index("ix_dynamic_alert_external_alert_source_id_source_type")
        batch_op.drop_column("external_alert_source_type")
        batch_op.drop_column("external_alert_source_id")

    with op.batch_alter_table("dynamic_alert_time_series_history", schema=None) as batch_op:
        batch_op.drop_column("external_alert_source_type")
        batch_op.drop_column("external_alert_source_id")

    # ### end Alembic commands ###
