"""Migration

Revision ID: ab24602a9f68
Revises: b6cca7c6d99c
Create Date: 2024-05-10 21:42:27.125458

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ab24602a9f68"
down_revision = "b6cca7c6d99c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "autofix_pr_id_to_run_id",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("pr_id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run_state.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "pr_id", "run_id"),
    )
    with op.batch_alter_table("autofix_pr_id_to_run_id", schema=None) as batch_op:
        batch_op.create_index(
            "ix_autofix_pr_id_to_run_id_provider_pr_id", ["provider", "pr_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("autofix_pr_id_to_run_id", schema=None) as batch_op:
        batch_op.drop_index("ix_autofix_pr_id_to_run_id_provider_pr_id")

    op.drop_table("autofix_pr_id_to_run_id")
    # ### end Alembic commands ###
