"""Migration

Revision ID: ad9f58463230
Revises: 82a6d42b94cf
Create Date: 2024-03-13 21:07:02.812894

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ad9f58463230"
down_revision = "82a6d42b94cf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.add_column(sa.Column("stacktrace_hash", sa.String(length=32), nullable=True))
        batch_op.alter_column("group_id", existing_type=sa.BIGINT(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.alter_column("group_id", existing_type=sa.BIGINT(), nullable=False)
        batch_op.drop_column("stacktrace_hash")

    # ### end Alembic commands ###
