"""Archive_last_downloaded_at

Revision ID: b27f28d90e1a
Revises: ac95ebfa16cb
Create Date: 2025-05-29 17:36:08.913699

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b27f28d90e1a"
down_revision = "ac95ebfa16cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("seer_repo_archive", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_downloaded_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("seer_repo_archive", schema=None) as batch_op:
        batch_op.drop_column("last_downloaded_at")

    # ### end Alembic commands ###
