"""Migration

Revision ID: b3c104475ec4
Revises: 95224c23dc7a
Create Date: 2024-02-16 20:20:36.889658

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b3c104475ec4"
down_revision = "95224c23dc7a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_line_number", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.drop_column("last_line_number")

    # ### end Alembic commands ###
