"""Migration

Revision ID: b6cca7c6d99c
Revises: 7278a2303b10
Create Date: 2024-05-08 17:36:15.668260

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b6cca7c6d99c"
down_revision = "7278a2303b10"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.drop_column("stacktrace_hash")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("stacktrace_hash", sa.VARCHAR(length=32), autoincrement=False, nullable=True)
        )

    # ### end Alembic commands ###
