"""Migration

Revision ID: b73740e52f3e
Revises: b3c104475ec4
Create Date: 2024-02-16 22:02:30.823191

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b73740e52f3e"
down_revision = "b3c104475ec4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("language", sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.drop_column("language")

    # ### end Alembic commands ###
