"""Migration

Revision ID: b96b4ed54450
Revises: 384911696acd
Create Date: 2025-02-22 00:24:56.629598

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b96b4ed54450"
down_revision = "384911696acd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prophet_alert_time_series", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.Integer(),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "dynamic_alert_id",
            existing_type=sa.BIGINT(),
            type_=sa.Integer(),
            existing_nullable=False,
        )
        batch_op.create_foreign_key(
            None, "dynamic_alerts", ["dynamic_alert_id"], ["id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prophet_alert_time_series", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.alter_column(
            "dynamic_alert_id",
            existing_type=sa.Integer(),
            type_=sa.BIGINT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.Integer(),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    # ### end Alembic commands ###
