"""Migration

Revision ID: c49dbef31dc8
Revises: 5618a759ab14
Create Date: 2024-04-12 20:52:05.426291

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c49dbef31dc8"
down_revision = "5618a759ab14"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("codebase_namespaces", schema=None) as batch_op:
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("accessed_at", sa.DateTime(), nullable=False))
        batch_op.create_index("ix_codebase_namespace_repo_id_sha", ["repo_id", "sha"], unique=False)
        batch_op.create_index(
            "ix_codebase_namespace_repo_id_tracking_branch",
            ["repo_id", "tracking_branch"],
            unique=False,
        )

    with op.batch_alter_table("repositories", schema=None) as batch_op:
        batch_op.create_index(
            "ix_repository_organization_project_provider_slug",
            ["organization", "project", "provider", "external_slug"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repositories", schema=None) as batch_op:
        batch_op.drop_index("ix_repository_organization_project_provider_slug")

    with op.batch_alter_table("codebase_namespaces", schema=None) as batch_op:
        batch_op.drop_index("ix_codebase_namespace_repo_id_tracking_branch")
        batch_op.drop_index("ix_codebase_namespace_repo_id_sha")
        batch_op.drop_column("accessed_at")
        batch_op.drop_column("updated_at")

    # ### end Alembic commands ###
