"""remove seer pref created_at

Revision ID: c534539c3752
Revises: 14b69932f015
Create Date: 2025-03-26 18:34:29.881073

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c534539c3752"
down_revision = "14b69932f015"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("seer_project_preferences", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("seer_project_preferences", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False)
        )

    # ### end Alembic commands ###
