"""Issue Fixability

Revision ID: cac994b711d3
Revises: e0fcdc14251c
Create Date: 2025-03-11 22:56:02.723357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac994b711d3'
down_revision = 'e0fcdc14251c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fixability_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_fixable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fixability_score_version', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_summary', schema=None) as batch_op:
        batch_op.drop_column('fixability_score_version')
        batch_op.drop_column('is_fixable')
        batch_op.drop_column('fixability_score')

    # ### end Alembic commands ###
