"""Llm blacklisting

Revision ID: cc6c5ff5f08c
Revises: 1c4ab1bd7b98
Create Date: 2025-06-06 20:41:35.560122

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cc6c5ff5f08c"
down_revision = "1c4ab1bd7b98"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_region_blacklist",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("provider_name", sa.String(), nullable=False),
        sa.Column("model_name", sa.String(), nullable=False),
        sa.Column("region", sa.String(), nullable=False),
        sa.Column("blacklisted_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("failure_reason", sa.String(), nullable=True),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_name", "model_name", "region", "blacklisted_at"),
    )
    with op.batch_alter_table("llm_region_blacklist", schema=None) as batch_op:
        batch_op.create_index("ix_llm_region_blacklist_expires_at", ["expires_at"], unique=False)
        batch_op.create_index(
            "ix_llm_region_blacklist_provider_model", ["provider_name", "model_name"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_region_blacklist", schema=None) as batch_op:
        batch_op.drop_index("ix_llm_region_blacklist_provider_model")
        batch_op.drop_index("ix_llm_region_blacklist_expires_at")

    op.drop_table("llm_region_blacklist")
    # ### end Alembic commands ###
