"""Migration

Revision ID: cf86143993dd
Revises: 913d11ce1bea
Create Date: 2024-03-27 18:47:41.331734

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cf86143993dd"
down_revision = "913d11ce1bea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "codebase_namespaces",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("repo_id", sa.Integer(), nullable=False),
        sa.Column("sha", sa.String(length=40), nullable=False),
        sa.Column("tracking_branch", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["repo_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repo_id", "sha"),
        sa.UniqueConstraint("repo_id", "tracking_branch"),
    )
    with op.batch_alter_table("repositories", schema=None) as batch_op:
        batch_op.add_column(sa.Column("default_namespace", sa.Integer(), nullable=True))
        batch_op.alter_column("sha", existing_type=sa.VARCHAR(length=40), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repositories", schema=None) as batch_op:
        batch_op.alter_column("sha", existing_type=sa.VARCHAR(length=40), nullable=False)
        batch_op.drop_column("default_namespace")

    op.drop_table("codebase_namespaces")
    # ### end Alembic commands ###
