"""Migration

Revision ID: d1214acbe7bc
Revises: f77d67f765e5
Create Date: 2024-06-12 19:03:53.627139

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d1214acbe7bc"
down_revision = "f77d67f765e5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.drop_column("group_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.add_column(sa.Column("group_id", sa.BIGINT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
