"""Migration

Revision ID: d8b8874b594d
Revises: c49dbef31dc8
Create Date: 2024-04-16 16:55:31.958762

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d8b8874b594d"
down_revision = "c49dbef31dc8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "run_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.BigInteger(), nullable=True),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("repositories", schema=None) as batch_op:
        batch_op.drop_column("sha")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repositories", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("sha", sa.VARCHAR(length=40), autoincrement=False, nullable=True)
        )

    op.drop_table("run_state")
    # ### end Alembic commands ###
