"""Migration

Revision ID: da0a9c9f1bb4
Revises: 262096f18cd1
Create Date: 2024-09-06 20:34:49.099486

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "da0a9c9f1bb4"
down_revision = "262096f18cd1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run_state", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("type", sa.String(), nullable=False, server_default="autofix")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run_state", schema=None) as batch_op:
        batch_op.drop_column("type")

    # ### end Alembic commands ###
