"""Migration

Revision ID: e54b8e278c2d
Revises: 3914e6cdb818
Create Date: 2024-10-28 22:53:23.766432

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e54b8e278c2d"
down_revision = "3914e6cdb818"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.add_column(sa.Column("message", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.drop_column("message")

    # ### end Alembic commands ###
