"""Migration

Revision ID: ee9136e6ff84
Revises: e0fcdc14251c
Create Date: 2025-03-06 14:31:33.084873

"""

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector  # type: ignore
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ee9136e6ff84"
down_revision = "e0fcdc14251c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_comments_embedding",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("owner", sa.String(), nullable=False),
        sa.Column("repo", sa.String(), nullable=False),
        sa.Column("pr_id", sa.BigInteger(), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("is_good_pattern", sa.Boolean(), nullable=False),
        sa.Column("embedding", Vector(dim=768), nullable=False),
        sa.Column("comment_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "pr_id", "repo", "owner"),
    )
    with op.batch_alter_table("review_comments_embedding", schema=None) as batch_op:
        batch_op.create_index(
            "ix_review_comments_embedding_hnsw",
            ["embedding"],
            unique=False,
            postgresql_using="hnsw",
            postgresql_with={"m": 16, "ef_construction": 200},
            postgresql_ops={"embedding": "vector_cosine_ops"},
        )
        batch_op.create_index(
            "ix_review_comments_is_good_pattern", ["is_good_pattern"], unique=False
        )
        batch_op.create_index(
            "ix_review_comments_repo_owner_pr", ["owner", "repo", "pr_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("review_comments_embedding", schema=None) as batch_op:
        batch_op.drop_index("ix_review_comments_repo_owner_pr")
        batch_op.drop_index("ix_review_comments_is_good_pattern")
        batch_op.drop_index(
            "ix_review_comments_embedding_hnsw",
            postgresql_using="hnsw",
            postgresql_with={"m": 16, "ef_construction": 200},
            postgresql_ops={"embedding": "vector_cosine_ops"},
        )

    op.drop_table("review_comments_embedding")
    # ### end Alembic commands ###
