"""Migration

Revision ID: f1970ed945bd
Revises: cac994b711d3
Create Date: 2025-03-20 13:48:53.089598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1970ed945bd'
down_revision = 'cac994b711d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codegen_unit_test_generation_pr_context_to_run_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('pr_id', sa.BigInteger(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('original_pr_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run_state.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'pr_id', 'repo', 'owner', 'original_pr_url')
    )
    with op.batch_alter_table('codegen_unit_test_generation_pr_context_to_run_id', schema=None) as batch_op:
        batch_op.create_index('ix_unit_test_context_repo_owner_pr_id_pr_url', ['owner', 'repo', 'pr_id', 'original_pr_url'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codegen_unit_test_generation_pr_context_to_run_id', schema=None) as batch_op:
        batch_op.drop_index('ix_unit_test_context_repo_owner_pr_id_pr_url')

    op.drop_table('codegen_unit_test_generation_pr_context_to_run_id')
    # ### end Alembic commands ###
