"""Migration

Revision ID: f77d67f765e5
Revises: 0a992db1f362
Create Date: 2024-06-06 00:18:47.804741

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "f77d67f765e5"
down_revision = "0a992db1f362"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.create_unique_constraint("u_project_id_hash", ["project_id", "hash"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.drop_constraint("u_project_id_hash", type_="unique")

    # ### end Alembic commands ###
