"""Migration

Revision ID: f9ce14f26c04
Revises: 1939547a1261
Create Date: 2024-04-30 20:50:33.616686

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f9ce14f26c04"
down_revision = "1939547a1261"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "group_hash",
                sa.String(length=32),
                server_default="00000000000000000000000000000000",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouping_records", schema=None) as batch_op:
        batch_op.drop_column("group_hash")

    # ### end Alembic commands ###
