"""repo_syncing

Revision ID: fc708616c38b
Revises: 9ac60c7534ce
Create Date: 2025-05-27 21:16:15.639716

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fc708616c38b"
down_revision = "9ac60c7534ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("seer_backfill_state", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            type_=sa.BigInteger(),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "backfill_cursor",
            existing_type=sa.INTEGER(),
            type_=sa.BigInteger(),
            existing_nullable=False,
        )
        batch_op.drop_column("task_taken_key")

    # Delete all existing repo archives
    op.execute("DELETE FROM seer_repo_archive")

    with op.batch_alter_table("seer_repo_archive", schema=None) as batch_op:
        batch_op.add_column(sa.Column("repo_definition", sa.JSON(), nullable=False, default={}))
        batch_op.add_column(
            sa.Column("updated_at", sa.DateTime(), nullable=False, default=sa.func.now())
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("seer_repo_archive", schema=None) as batch_op:
        batch_op.drop_column("updated_at")
        batch_op.drop_column("repo_definition")

    with op.batch_alter_table("seer_backfill_state", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("task_taken_key", sa.VARCHAR(), autoincrement=False, nullable=True)
        )
        batch_op.alter_column(
            "backfill_cursor",
            existing_type=sa.BigInteger(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger(),
            type_=sa.INTEGER(),
            existing_nullable=False,
            autoincrement=True,
        )

    # ### end Alembic commands ###
