# More information on gocd-flavor YAML can be found here:
# - https://github.com/tomzo/gocd-yaml-config-plugin#pipeline
# - https://www.notion.so/sentry/GoCD-New-Service-Quickstart-6d8db7a6964049b3b0e78b8a4b52e25d
format_version: 10
pipelines:
    deploy-seer:
        environment_variables:
            GCP_PROJECT: internal-sentry
            GKE_CLUSTER: zdpwkxst
            GKE_REGION: us-central1
            GKE_CLUSTER_ZONE: b
            GKE_BASTION_ZONE: b
        group: seer
        lock_behavior: unlockWhenFinished
        materials:
            seer_repo:
                git: git@github.com:getsentry/seer.git
                shallow_clone: true
                branch: main
                destination: seer
        stages:
            - checks:
                  approval:
                      type: manual
                  jobs:
                      checks:
                          environment_variables:
                              # Required for checkruns.
                              GITHUB_TOKEN: "{{SECRET:[devinfra-github][token]}}"
                          timeout: 1200
                          elastic_profile_id: seer
                          tasks:
                              - script: |
                                    /devinfra/scripts/checks/githubactions/checkruns.py \
                                    getsentry/seer \
                                    ${GO_REVISION_SEER_REPO} \
                                    build
                              - script: |
                                    /devinfra/scripts/checks/googlecloud/checkcloudbuild.py \
                                    ${GO_REVISION_SEER_REPO} \
                                    sentryio \
                                    "us.gcr.io/sentryio/seer"
            - deploy:
                  jobs:
                    run-migrations:
                      timeout: 1200
                      elastic_profile_id: seer
                      tasks:
                        - script: |
                            echo "running flask db upgrade" \
                            && /devinfra/scripts/k8s/k8stunnel \
                            && /devinfra/scripts/k8s/k8s-spawn-job.py \
                            --container-name="seer" \
                            --label-selector="service=seer" \
                            "seer-run-migrations" \
                            "us.gcr.io/sentryio/seer:${GO_REVISION_SEER_REPO}" \
                            -- \
                            flask \
                            db \
                            upgrade

                    deploy:
                        timeout: 1200
                        elastic_profile_id: seer
                        tasks:
                            - script: |
                                  /devinfra/scripts/k8s/k8stunnel \
                                  && /devinfra/scripts/k8s/k8s-deploy.py \
                                  --label-selector="service=seer" \
                                  --image="us.gcr.io/sentryio/seer:${GO_REVISION_SEER_REPO}" \
                                  --container-name="seer"
                            - script: |
                                  /devinfra/scripts/k8s/k8stunnel \
                                  && /devinfra/scripts/k8s/k8s-deploy.py \
                                  --label-selector="service=seer-autofix" \
                                  --image="us.gcr.io/sentryio/seer:${GO_REVISION_SEER_REPO}" \
                                  --container-name="seer-autofix"
