# More information on gocd-flavor YAML can be found here:
# - https://github.com/tomzo/gocd-yaml-config-plugin#pipeline
# - https://www.notion.so/sentry/GoCD-New-Service-Quickstart-6d8db7a6964049b3b0e78b8a4b52e25d
format_version: 10
pipelines:
    deploy-timeseries-analysis-service:
        environment_variables:
            GCP_PROJECT: internal-sentry
            GKE_CLUSTER: zdpwkxst
            GKE_REGION: us-central1
            GKE_CLUSTER_ZONE: b
            GKE_BASTION_ZONE: b
        group: timeseries-analysis-service
        lock_behavior: unlockWhenFinished
        materials:
            timeseries_analysis_service_repo:
                git: git@github.com:getsentry/timeseries-analysis-service.git
                shallow_clone: true
                branch: main
                destination: timeseries-analysis-service
        stages:
            - checks:
                  approval:
                      type: manual
                  jobs:
                      checks:
                          environment_variables:
                              # Required for checkruns.
                              GITHUB_TOKEN: "{{SECRET:[devinfra-github][token]}}"
                          timeout: 1200
                          elastic_profile_id: timeseries-analysis-service
                          tasks:
                              - script: |
                                    /devinfra/scripts/checks/githubactions/checkruns.py \
                                    getsentry/timeseries-analysis-service \
                                    ${GO_REVISION_TIMESERIES_ANALYSIS_SERVICE_REPO} \
                                    build
                              - script: |
                                    /devinfra/scripts/checks/googlecloud/checkcloudbuild.py \
                                    ${GO_REVISION_TIMESERIES_ANALYSIS_SERVICE_REPO} \
                                    sentryio \
                                    "us.gcr.io/sentryio/seer"
            - deploy:
                  jobs:
                      deploy:
                          timeout: 1200
                          elastic_profile_id: timeseries-analysis-service
                          tasks:
                              - script: |
                                    /devinfra/scripts/k8s/k8stunnel \
                                    && /devinfra/scripts/k8s/k8s-deploy.py \
                                    --label-selector="service=seer" \
                                    --image="us.gcr.io/sentryio/seer:${GO_REVISION_TIMESERIES_ANALYSIS_SERVICE_REPO}" \
                                    --container-name="seer"
                              - script: |
                                    /devinfra/scripts/k8s/k8stunnel \
                                    && /devinfra/scripts/k8s/k8s-deploy.py \
                                    --label-selector="service=seer-autofix" \
                                    --image="us.gcr.io/sentryio/seer:${GO_REVISION_TIMESERIES_ANALYSIS_SERVICE_REPO}" \
                                    --container-name="seer-autofix"
