AUTOFIX_ROOT_CAUSE_HARD_TIME_LIMIT_SECS = 60 * 15
AUTOFIX_ROOT_CAUSE_SOFT_TIME_LIMIT_SECS = 60 * 10

AUTOFIX_EXECUTION_HARD_TIME_LIMIT_SECS = 60 * 15
AUTOFIX_EXECUTION_SOFT_TIME_LIMIT_SECS = 60 * 10

AUTOFIX_HARD_TIME_OUT_MINS = 10
AUTOFIX_UPDATE_TIMEOUT_SECS = 90
