AUTOFIX_CREATE_INDEX_SOFT_TIME_LIMIT_SECS = 60 * 45
AUTOFIX_CREATE_INDEX_HARD_TIME_LIMIT_SECS = 60 * 50

AUTOFIX_UPDATE_INDEX_SOFT_TIME_LIMIT_SECS = 60 * 20
AUTOFIX_UPDATE_INDEX_HARD_TIME_LIMIT_SECS = 60 * 30

AUTOFIX_ROOT_CAUSE_HARD_TIME_LIMIT_SECS = 60 * 15
AUTOFIX_ROOT_CAUSE_SOFT_TIME_LIMIT_SECS = 60 * 10

AUTOFIX_EXECUTION_HARD_TIME_LIMIT_SECS = 60 * 15
AUTOFIX_EXECUTION_SOFT_TIME_LIMIT_SECS = 60 * 10

AUTOFIX_HARD_TIME_OUT_SECS = 60 * 60  # 1 hour
