"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ScoreRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    HAS_STACKTRACE_FIELD_NUMBER: builtins.int
    HANDLED_FIELD_NUMBER: builtins.int
    TRIGGER_TIMEOUT_FIELD_NUMBER: builtins.int
    TRIGGER_ERROR_FIELD_NUMBER: builtins.int
    message: builtins.str
    has_stacktrace: builtins.int
    """Really a boolean, but historically a non-zero integer."""
    handled: builtins.bool
    trigger_timeout: builtins.bool
    """Some silly debug flags, likely will be deprecated, but here for demo completeness"""
    trigger_error: builtins.bool
    def __init__(
        self,
        *,
        message: builtins.str = ...,
        has_stacktrace: builtins.int = ...,
        handled: builtins.bool = ...,
        trigger_timeout: builtins.bool = ...,
        trigger_error: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["handled", b"handled", "has_handled", b"has_handled"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["handled", b"handled", "has_handled", b"has_handled", "has_stacktrace", b"has_stacktrace", "message", b"message", "trigger_error", b"trigger_error", "trigger_timeout", b"trigger_timeout"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["has_handled", b"has_handled"]) -> typing.Literal["handled"] | None: ...

global___ScoreRequest = ScoreRequest

@typing.final
class ScoreResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SEVERITY_FIELD_NUMBER: builtins.int
    severity: builtins.float
    def __init__(
        self,
        *,
        severity: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["severity", b"severity"]) -> None: ...

global___ScoreResponse = ScoreResponse
