# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sentry_services/seer/severity.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n#sentry_services/seer/severity.proto\x12\x0fsentry_rpc.seer"\x89\x01\n\x0cScoreRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x16\n\x0ehas_stacktrace\x18\x02 \x01(\x05\x12\x11\n\x07handled\x18\x03 \x01(\x08H\x00\x12\x17\n\x0ftrigger_timeout\x18\x04 \x01(\x08\x12\x15\n\rtrigger_error\x18\x05 \x01(\x08\x42\r\n\x0bhas_handled"!\n\rScoreResponse\x12\x10\n\x08severity\x18\x01 \x01(\x01\x32Z\n\x08Severity\x12N\n\rGetIssueScore\x12\x1d.sentry_rpc.seer.ScoreRequest\x1a\x1e.sentry_rpc.seer.ScoreResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "sentry_services.seer.severity_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_SCOREREQUEST"]._serialized_start = 57
    _globals["_SCOREREQUEST"]._serialized_end = 194
    _globals["_SCORERESPONSE"]._serialized_start = 196
    _globals["_SCORERESPONSE"]._serialized_end = 229
    _globals["_SEVERITY"]._serialized_start = 231
    _globals["_SEVERITY"]._serialized_end = 321
# @@protoc_insertion_point(module_scope)
