# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from sentry_services.seer import severity_pb2 as sentry__services_dot_seer_dot_severity__pb2


class SeverityStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIssueScore = channel.unary_unary(
            "/sentry_rpc.seer.Severity/GetIssueScore",
            request_serializer=sentry__services_dot_seer_dot_severity__pb2.ScoreRequest.SerializeToString,
            response_deserializer=sentry__services_dot_seer_dot_severity__pb2.ScoreResponse.FromString,
        )


class SeverityServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetIssueScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SeverityServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetIssueScore": grpc.unary_unary_rpc_method_handler(
            servicer.GetIssueScore,
            request_deserializer=sentry__services_dot_seer_dot_severity__pb2.ScoreRequest.FromString,
            response_serializer=sentry__services_dot_seer_dot_severity__pb2.ScoreResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "sentry_rpc.seer.Severity", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Severity(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetIssueScore(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/sentry_rpc.seer.Severity/GetIssueScore",
            sentry__services_dot_seer_dot_severity__pb2.ScoreRequest.SerializeToString,
            sentry__services_dot_seer_dot_severity__pb2.ScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
