# Constants used across the workflow
EMPTY_VALUE_ATTRIBUTE = "EMPTY_VALUE"
DEFAULT_ALPHA = 10**-6
DEFAULT_K_RRF = 60

# Default weights
DEFAULT_KL_DIVERGENCE_WEIGHT = 0.8
DEFAULT_ENTROPY_WEIGHT = 0.2
