name: Linting

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      statuses: write

    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changes
        uses: dorny/paths-filter@0bc4621a3135347011ad047f9ecf449bf72ce2bd # v3.0.0
        with:
          # Paths to files will be available in `${FILTER_NAME}_files` output variable.
          list-files: json
          filters: |
            all:
              - added|modified: '**/*'

      - uses: getsentry/action-setup-venv@3a832a9604b3e1a4202ae559248f26867b467cc7 # v2.1.1
        with:
          python-version: 3.11.8
          cache-dependency-path: |
            requirements.txt
          install-cmd: pip install -r requirements-precommit.txt
      - name: Setup pre-commit
        run: |
          pre-commit install

      - name: Run pre-commit on PR commits
        id: pre-commit_results
        continue-on-error: true
        run: |
          jq '.[]' --raw-output <<< '${{steps.changes.outputs.all_files}}' |
            # Run pre-commit to check files that were changed (but not deleted) compared to master.
            # --show-diff-on-failure will display what needs to be fixed without making changes
            xargs pre-commit run --show-diff-on-failure --files

      - name: Get auth token
        id: token
        if: ${{ steps.pre-commit_results.outcome == 'failure' }}
        uses: getsentry/action-github-app-token@v3.0.0
        with:
          app_id: ${{ vars.SENTRY_INTERNAL_APP_ID }}
          private_key: ${{ secrets.SENTRY_INTERNAL_APP_PRIVATE_KEY }}

      - name: Apply any pre-commit fixed files
        if: ${{ steps.pre-commit_results.outcome == 'failure' }}
        # note: this runs "always" or else it's skipped when pre-commit fails
        uses: getsentry/action-github-commit@v2.1.0
        with:
          github-token: ${{ steps.token.outputs.token }}
          message: ":hammer_and_wrench: apply pre-commit fixes"

      - name: Fail job if pre-commit failed
        if: ${{ steps.pre-commit_results.outcome == 'failure' }}
        run: |
          echo "Pre-commit checks failed. Please fix the issues and try again."
          exit 1
