name: Relevant Warnings Check

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  relevant-warnings:
    name: Relevant Warnings
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5
        with:
          python-version: '3.11'

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Install Static Analysis Tools
        run: |
          pip install mypy==1.15.0
          pip install ruff==0.11.1

      - name: Install Overwatch CLI
        run: |
          curl -o overwatch-cli https://overwatch.codecov.io/linux/cli
          chmod +x overwatch-cli

      - name: Run Overwatch CLI
        run: |
          ./overwatch-cli \
            --url https://overwatch.codecov.io \
            --auth-token ${{ secrets.OVERWATCH_SENTRY_AUTH_TOKEN }} \
            --organization-slug sentry \
            python \
            --tool ruff
