name: Relevant Warnings

on:
  pull_request:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  relevant-warnings:
    name: Relevant Warnings
    runs-on: ubuntu-latest

  # TODO: Move over the stuff from other file
