name: Relevant Warnings

on:
  pull_request:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  relevant-warnings:
    name: Relevant Warnings
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Requirements
        run: |
          pip install -r requirements.txt
      - name: Install libssl (overwatch-cli requires OpenSSL 1.1)
        run: |
          sudo apt-get update
          wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb

      - name: Install Static Analysis Tools
        run: |
          pip install mypy==1.15.0
          pip install ruff==0.3.3

      - name: Install Overwatch CLI
        run: |
          curl -o overwatch-cli https://overwatch.codecov.io/linux/cli
          chmod +x overwatch-cli

      - name: Run Overwatch CLI
        run: |
          ./overwatch-cli \
            --auth-token ${{ secrets.OVERWATCH_SENTRY_AUTH_TOKEN }} \
            --organization-slug sentry \
            python
