name: Tests

on:
  push:
    branches: [main, experimental]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    # required for google auth
    permissions:
      contents: "read"
      id-token: "write"

    env:
      TEST: 1
      EXTRA_COMPOSE_TEST_OPTIONS: "-e NO_REAL_MODELS=1 -e NO_SENTRY_INTEGRATION=1"

    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/868781662168/locations/global/workloadIdentityPools/prod-github/providers/github-oidc-pool"
          service_account: "gha-seer-models@sac-prod-sa.iam.gserviceaccount.com"
          token_format: "id_token"
          id_token_audience: "610575311308-9bsjtgqg4jm01mt058rncpopujgk3627.apps.googleusercontent.com"
          id_token_include_email: true
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Fetch models + Build image
        run: |
          rm -rf ./models
          gcloud storage cp -r gs://sentry-ml/seer/models ./
      - name: Build image
        run: |
          make update
      - name: Typecheck with mypy
        run: |
          make mypy
      - name: Validate no pending migrations
        run: |
          make check-no-pending-migrations
      - name: Test with pytest
        run: |
          make test
      - name: Upload to codecov
        if: ${{ always() }}
        uses: codecov/codecov-action@e0b68c6749509c5f83f984dd99a76a1c1a231044 # v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ".artifacts/coverage.xml"
          override_commit: ${{ github.event.pull_request.head.sha }}
          plugin: noop
          verbose: true
