name: Tests

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST: 1
      NO_SENTRY_INTEGRATION: 1
      NO_REAL_MODELS: 1

    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: |
          make update
      - name: Typecheck with mypy
        run: |
          make mypy
      - name: Test with pytest
        run: |
          make test
